### ISSUE TITLE
余計なファイルを削除する

### ISSUE THREAD

**Issue by piro0919** [mp-gumi/training-kaneko-1#6]
**Is your feature request related to a problem? Please describe.**
Create React App 導入時に不要なファイルが作成されている。

**Describe the solution you'd like**
不要なファイルを削除する。

**Comment by mp-gumi** [comment]
見た感じApp.css, App.test.tsx, index.css, logo.svg は不要なのかなと思ったのですが、どのファイルを削除したらいいですか？
@piro0919

**Comment by piro0919** [comment]
@mp-gumi 

> 見た感じApp.css, App.test.tsx, index.css, logo.svg は不要なのかなと思ったのですが、どのファイルを削除したらいいですか？

上記に加え `App.tsx` ファイルも不要なので削除しちゃってください。 😸 

あと、削除するファイルへの参照が存在する場合は同時に消しちゃってください。 👍
